version: '3.1'

volumes:
  postgres:
  redis:
  assets:

services:
  db:
    image: postgres:9.6
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kuberton-shop_production
    volumes:
      - postgres:/var/lib/postgresql/data

  in_memory_store:
    image: redis:3.2-alpine
    expose:
      - 6379
    volumes:
      - redis:/var/lib/redis/data

  server_app: &server_app
    build: .
    command: bundle exec puma -C config/puma.rb
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ''
      # DB_HOST: db
      # DB_PORT: 5432
      # DB_NAME: kuberton-shop_production
      # DB_USERNAME: postgres
      # DB_PASSWORD: postgres
      # SECRET_KEY_BASE: STUB
      # DEVISE_SECRET_KEY: STUB
      # REDIS_URL: "redis://in_memory_store:6379"
    volumes:
      - assets:/home/www/kuberton-shop/public/assets
    depends_on:
      - db
      - in_memory_store
    expose:
      - 8000

  web_server:
    build: ./docker/nginx
    ports:
      - 80:8080
    environment:
      CUSTOM_APP_VHOST: server_app
    depends_on:
      - server_app
    volumes:
      - assets:/home/www/kuberton-shop/public/assets
