version: '3.1'

volumes:
  postgres:
  redis:
  bundle:

services:
  db:
    image: postgres:9.6
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kuberton-shop_development
    volumes:
      - postgres:/var/lib/postgresql/data

  in_memory_store:
    image: redis:3.2-alpine
    expose:
      - 6379
    volumes:
      - redis:/var/lib/redis/data

  server_app: &server_app
    build: .
    command: bundle exec rails server --binding 0.0.0.0
    volumes:
      - bundle:/home/www/kuberton-shop/vendor/bundle
      - ./app:/home/www/kuberton-shop/app # Указываем, что директория app и vendor/assets в контейнере будут ссылаться на директории в Host OS (локальная нода). Таким образом, нам будет доступен hot reload приложения
      - ./vendor/assets:/home/www/kuberton-shop/vendor/assets
      - ./public:/home/www/kuberton-shop/public
      - ./tmp:/home/www/kuberton-shop/tmp
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: kuberton-shop_development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SECRET_KEY_BASE: STUB
      DEVISE_SECRET_KEY: STUB
      REDIS_URL: "redis://in_memory_store:6379"
    depends_on:
      - db
      - in_memory_store
    ports:
      - 3000:3000
