development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: 82a01d08e8908f286e6e639856813e024edccafa93fe7d5321ed2eb1b2df9c01318d8c93a2f99394644ddf5747b129e3affb9fb9dbf1daf2037a75d730483c49

dev:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
